[component]
structures = [ "content_blocks" ]
label = "Projects"
description = "Projects Section with heading, a description and a link"
icon = "wysiwyg"
tags = ["Content"]

[props]
title = "Achievements + Projects"
description_html = "Following are my Projects and Various Acheivements"
link_url = "/projects"
show_projects = true